Models/Tablero.cs
using tl2_tp10_2023_NicoMagro.ViewModels.Tableros;

namespace tl2_tp10_2023_NicoMagro.Models
{
    public class Tablero
    {
        public int Id { get; set; }
        public int IdUsuarioPropietario { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }

        public Tablero()
        {

        }

        public Tablero(CrearTableroViewModel vm)
        {
            this.IdUsuarioPropietario = vm.IdUsuarioPropietario;
            this.Nombre = vm.Nombre;
            this.Descripcion = vm.Descripcion;
        }

        public Tablero(ModificarTableroViewModel vm)
        {
            this.IdUsuarioPropietario = vm.IdUsuarioPropietario;
            this.Nombre = vm.Nombre;
            this.Descripcion = vm.Descripcion;
        }
    }
}

ViewModels/Tableros/CrearTableroViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using tl2_tp10_2023_NicoMagro.Models;

namespace tl2_tp10_2023_NicoMagro.ViewModels.Tableros
{
    public class CrearTableroViewModel
    {
        [Display(Name = "Id del usuario propietario")]
        public int IdUsuarioPropietario { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(100, ErrorMessage = "El nombre del tablero no puede contener mas de 100 caracteres")]
        [Display(Name = "Nombre del tablero")]
        public string Nombre { get; set; }

        [Display(Name = "Descripción")]
        [StringLength(200, ErrorMessage = "La descripción del tablero no puede contener mas de 200 caracteres")]
        public string Descripcion { get; set; }


        public CrearTableroViewModel()
        {

        }

        public CrearTableroViewModel(Tablero tablero)
        {
            this.IdUsuarioPropietario = tablero.IdUsuarioPropietario;
            this.Nombre = tablero.Nombre;
            this.Descripcion = tablero.Descripcion;
        }
    }
}

ViewModels/Tableros/ListarTablerosViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using tl2_tp10_2023_NicoMagro.Models;

namespace tl2_tp10_2023_NicoMagro.ViewModels.Tableros
{
    public class ListarTablerosViewModel
    {
        public List<Tablero> ListadoTableros { get; set; }


        public ListarTablerosViewModel()
        {

        }

        public ListarTablerosViewModel(List<Tablero> tableros)
        {
            this.ListadoTableros = tableros;
        }
    }
}

ViewModels/Tableros/ModificarTableroViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using tl2_tp10_2023_NicoMagro.Models;

namespace tl2_tp10_2023_NicoMagro.ViewModels.Tableros
{
    public class ModificarTableroViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Id del usuario propietario")]
        public int IdUsuarioPropietario { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(100, ErrorMessage = "El nombre del tablero no puede contener mas de 100 caracteres")]
        [Display(Name = "Nombre del tablero")]
        public string Nombre { get; set; }

        [Display(Name = "Descripción")]
        [StringLength(200, ErrorMessage = "La descripción del tablero no puede contener mas de 200 caracteres")]
        public string Descripcion { get; set; }


        public ModificarTableroViewModel()
        {

        }

        public ModificarTableroViewModel(Tablero tablero)
        {
            this.IdUsuarioPropietario = tablero.IdUsuarioPropietario;
            this.Nombre = tablero.Nombre;
            this.Descripcion = tablero.Descripcion;
        }
    }
}

Controllers/TableroController.cs
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_NicoMagro.Repositories;
using tl2_tp10_2023_NicoMagro.Models;
using System.Diagnostics;
using tl2_tp10_2023_NicoMagro.ViewModels.Tableros;

namespace tl2_tp10_2023_NicoMagro.Controllers
{
    public class TableroController : Controller
    {
        private ITableroRepository repository;
        private readonly ILogger<TableroController> _logger;

        public TableroController(ILogger<TableroController> logger)
        {
            _logger = logger;
            repository = new TableroRepository();
        }

        public IActionResult Index()
        {
            if (!Logueado())
            {
                TempData["ErrorMessage"] = "No tienes permisos para editar un usuario";
                return RedirectToRoute(new { controller = "Login", action = "Index" });
            }
            if (!ModelState.IsValid) return RedirectToAction("EditarTarea");
            List<Tablero> tableros = repository.GetAll();
            ListarTablerosViewModel vm = new ListarTablerosViewModel(tableros);

            if (tableros != null)
            {
                return View(vm);
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public IActionResult CrearTablero()
        {
            if (!Logueado())
            {
                TempData["ErrorMessage"] = "No tienes permisos para editar un usuario";
                return RedirectToRoute(new { controller = "Login", action = "Index" });
            }
            if (!esAdmin())
            {
                TempData["ErrorMessage"] = "No tienes permisos para crear un tablero";
                return RedirectToAction("Index");
            }
            if (!ModelState.IsValid) return RedirectToAction("EditarTarea");
            return View(new CrearTableroViewModel());
        }

        [HttpPost]
        public IActionResult CrearTablero(CrearTableroViewModel vm)
        {
            if (!Logueado())
            {
                TempData["ErrorMessage"] = "No tienes permisos para editar un usuario";
                return RedirectToRoute(new { controller = "Login", action = "Index" });
            }
            if (!esAdmin())
            {
                TempData["ErrorMessage"] = "No tienes permisos para crear un tablero";
                return RedirectToAction("Index");
            }
            if (!ModelState.IsValid) return RedirectToAction("EditarTarea");


            var tablero = new Tablero(vm);
            repository.Create(tablero);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditarTablero(int id)
        {
            if (!Logueado())
            {
                TempData["ErrorMessage"] = "No tienes permisos para editar un usuario";
                return RedirectToRoute(new { controller = "Login", action = "Index" });
            }
            if (!esAdmin())
            {
                TempData["ErrorMessage"] = "No tienes permisos para crear un tablero";
                return RedirectToAction("Index");
            }
            if (!ModelState.IsValid) return RedirectToAction("EditarTarea");
            ModificarTableroViewModel vm = new ModificarTableroViewModel(repository.GetById(id));
            return View(vm);
        }

        [HttpPost]
        public IActionResult EditarTablero(ModificarTableroViewModel vm)
        {
            if (!Logueado())
            {
                TempData["ErrorMessage"] = "No tienes permisos para editar un usuario";
                return RedirectToRoute(new { controller = "Login", action = "Index" });
            }
            if (!esAdmin())
            {
                TempData["ErrorMessage"] = "No tienes permisos para crear un tablero";
                return RedirectToAction("Index");
            }
            if (!ModelState.IsValid) return RedirectToAction("EditarTarea");
            var userFromDb = new Tablero(vm);
            repository.Update(userFromDb.Id, userFromDb);


            return RedirectToAction("Index");
        }

        public IActionResult EliminarTablero(int Id)
        {
            try
            {
                if (!Logueado())
                {
                    TempData["ErrorMessage"] = "No tienes permisos para editar un usuario";
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
                if (!esAdmin())
                {
                    TempData["ErrorMessage"] = "No tienes permisos para crear un tablero";
                    return RedirectToAction("Index");
                }
                if (!ModelState.IsValid) return RedirectToAction("EditarTarea");
                repository.Remove(Id);

                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                _logger.LogError($"Error en el endpoint 'EliminarTablero'. Detalles: {ex.ToString()}");
                return ViewComponent("Error");
            }

        }

        public bool Logueado()
        {
            return HttpContext.Session.Keys.Any();
        }

        private bool esAdmin()
        {
            return HttpContext.Session.Keys.Any() && ((int)HttpContext.Session.GetInt32("rol") == 0);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Tablero/CrearTablero.cshtml
@model tl2_tp10_2023_NicoMagro.ViewModels.Tableros.CrearTableroViewModel

<form asp-controller="Tablero" asp-action="CrearTablero">
    <div class="mb-3" class="form-group">
        <label asp-for="@Model.IdUsuarioPropietario" class="form-label"></label>
        <input asp-for="@Model.IdUsuarioPropietario" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Nombre" class="form-label"></label>
        <input asp-for="@Model.Nombre" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Descripcion" class="form-label"></label>
        <input asp-for="@Model.Descripcion" class="form-control" />
    </div>

    <button type="submit" class="btn btn-info">Crear</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Tablero/EditarTablero.cshtml
@model tl2_tp10_2023_NicoMagro.ViewModels.Tableros.ModificarTableroViewModel

<form asp-controller="Tablero" asp-action="EditarTablero">
    <input hidden asp-for="@Model.Id">
    <div class="mb-3" class="form-group">
        <label asp-for="@Model.IdUsuarioPropietario" class="form-label"></label>
        <input asp-for="@Model.IdUsuarioPropietario" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Nombre" class="form-label"></label>
        <input asp-for="@Model.Nombre" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Descripcion" class="form-label"></label>
        <input asp-for="@Model.Descripcion" class="form-control" />
    </div>

    <button type="submit" class="btn btn-info">Editar</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Tablero/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model tl2_tp10_2023_NicoMagro.ViewModels.Tableros.ListarTablerosViewModel

<h2>Listado de Tableros</h2>

<table class="table table-success table-striped">
    <thead>
        <tr>
            <th hidden>ID</th>
            <th>Id usuario propietario</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tab in Model.ListadoTableros)
        {
            <tr>
                <td hidden>@tab.Id</td>
                <td>@tab.IdUsuarioPropietario</td>
                <td>@tab.Nombre</td>
                <td>@tab.Descripcion</td>
                <td>
                    <a asp-controller="Tablero" asp-action="EditarTablero" asp-route-id="@tab.Id"
                        class="btn btn-info">Editar</a>
                    <a asp-controller="Tablero" asp-action="EliminarTablero" asp-route-id="@tab.Id"
                        onclick="return confirm('¿Estás seguro que quieres eliminar el Tablero?')"
                        class="btn btn-outline-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}