Models/Tarea.cs
using tl2_tp10_2023_NicoMagro.ViewModels.Tareas;

namespace tl2_tp10_2023_NicoMagro.Models
{
    public class Tarea
    {
        public int Id { get; set; }
        public int Id_tablero { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Color { get; set; }
        public EstadoTarea Estado { get; set; }
        public int IdUsuarioAsignado { get; set; }

        public Tarea() { }

        public Tarea(CrearTareaViewModel vm)
        {
            this.Id_tablero = vm.IdTablero;
            this.Nombre = vm.Nombre;
            this.Descripcion = vm.Descripcion;
            this.Color = vm.Color;
            this.Estado = vm.Estado;
            this.IdUsuarioAsignado = vm.IdUsuarioAsignado;
        }

        public Tarea(ModificarTareaViewModel vm)
        {
            this.Id_tablero = vm.IdTablero;
            this.Nombre = vm.Nombre;
            this.Descripcion = vm.Descripcion;
            this.Color = vm.Color;
            this.Estado = vm.Estado;
            this.IdUsuarioAsignado = vm.IdUsuarioAsignado;
        }
    }

    public enum EstadoTarea
    {
        Ideas = 1,
        ToDo = 2,
        Doing = 3,
        Review = 4,
        Done = 5
    }
}

ViewModels/Tareas/CrearTareaViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using tl2_tp10_2023_NicoMagro.Models;


namespace tl2_tp10_2023_NicoMagro.ViewModels.Tareas
{
    public class CrearTareaViewModel
    {
        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Id del tablero")]
        public int IdTablero { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(100, ErrorMessage = "El nombre de la tarea no puede contener más de 100 caracteres")]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Display(Name = "Descripción")]
        [StringLength(200, ErrorMessage = "La descripción de la tarea no puede contener más de 200 caracteres")]
        public string Descripcion { get; set; }

        [Display(Name = "Color")]
        [StringLength(15, ErrorMessage = "El color de la tarea no puede contener más de 15 caracteres")]
        public string Color { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Estado")]
        public EstadoTarea Estado { get; set; }

        [Display(Name = "Id del usuario asignado")]
        public int IdUsuarioAsignado { get; set; }


        public CrearTareaViewModel()
        {

        }

        public CrearTareaViewModel(Tarea tarea)
        {
            this.IdTablero = tarea.Id_tablero;
            this.Nombre = tarea.Nombre;
            this.Descripcion = tarea.Descripcion;
            this.Color = tarea.Color;
            this.Estado = tarea.Estado;
            this.IdUsuarioAsignado = tarea.IdUsuarioAsignado;
        }
    }
}

ViewModels/Tareas/ListarTareasViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using tl2_tp10_2023_NicoMagro.Models;

namespace tl2_tp10_2023_NicoMagro.ViewModels.Tareas
{
    public class ListarTareasViewModel
    {
        public List<Tarea> ListadoTareas { get; set; }


        public ListarTareasViewModel()
        {

        }

        public ListarTareasViewModel(List<Tarea> tareas)
        {
            this.ListadoTareas = tareas;
        }
    }
}

ViewModels/Tareas/ModificarTareaViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using tl2_tp10_2023_NicoMagro.Models;


namespace tl2_tp10_2023_NicoMagro.ViewModels.Tareas
{
    public class ModificarTareaViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Id del tablero")]
        public int IdTablero { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(100, ErrorMessage = "El nombre de la tarea no puede contener mas de 100 caracteres")]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Display(Name = "Descripción")]
        [StringLength(200, ErrorMessage = "La descripción de la tarea no puede contener mas de 200 caracteres")]
        public string Descripcion { get; set; }

        [Display(Name = "Color")]
        [StringLength(15, ErrorMessage = "El color de la tarea no puede contener mas de 15 caracteres")]
        public string Color { get; set; }

        [Required(ErrorMessage = "Este campo es requerido.")]
        [Display(Name = "Estado")]
        public EstadoTarea Estado { get; set; }

        [Display(Name = "Id del usuario asignado")]
        public int IdUsuarioAsignado { get; set; }


        public ModificarTareaViewModel()
        {

        }

        public ModificarTareaViewModel(Tarea tarea)
        {
            this.Id = tarea.Id;
            this.IdTablero = tarea.Id_tablero;
            this.Nombre = tarea.Nombre;
            this.Descripcion = tarea.Descripcion;
            this.Color = tarea.Color;
            this.Estado = tarea.Estado;
            this.IdUsuarioAsignado = tarea.IdUsuarioAsignado;
        }
    }
}

Controllers/TareaController.cs
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_NicoMagro.Models;
using tl2_tp10_2023_NicoMagro.Repositories;
using System.Diagnostics;
using tl2_tp10_2023_NicoMagro.ViewModels.Tareas;

namespace tl2_tp10_2023_NicoMagro.Controllers
{
    public class TareaController : Controller
    {
        private ITareaRepository repository;
        private readonly ILogger<TareaController> _logger;

        public TareaController(ILogger<TareaController> logger)
        {
            _logger = logger;
            repository = new TareaRepository();
        }

        public IActionResult Index()
        {
            if (!Logueado())
            {
                return RedirectToRoute(new { controller = "Login", action = "Index" });
            }
            if (!ModelState.IsValid) return RedirectToAction("EditarTarea");

            List<Tarea> tareas = repository.GetAll();
            ListarTareasViewModel vm = new ListarTareasViewModel(tareas);

            if (tareas != null)
            {
                return View(vm);
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public IActionResult CrearTarea()
        {
            try
            {
                if (!Logueado())
                {
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
                if (!ModelState.IsValid) return RedirectToAction("EditarTarea");
                return View(new CrearTareaViewModel());
            }
            catch (System.Exception ex)
            {
                _logger.LogError($"Error en el endpoint 'CrearTarea'. Detalles: {ex.ToString()}");
                return View("Error");
            }
        }

        [HttpPost]
        public IActionResult CrearTarea(CrearTareaViewModel vm)
        {
            try
            {
                if (!Logueado())
                {
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
                if (!ModelState.IsValid) return RedirectToAction("EditarTarea");
                var task = new Tarea(vm);
                repository.Create(1, task);
                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                _logger.LogError($"Error en el endpoint 'CrearTarea'. Detalles: {ex.ToString()}");
                return View("Error");
            }
        }

        [HttpGet]
        public IActionResult EditarTarea(int id)
        {
            try
            {
                if (!Logueado())
                {
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
                if (!ModelState.IsValid) return RedirectToAction("EditarTarea");
                var vm = new ModificarTareaViewModel(repository.GetById(id));
                return View(vm);
            }
            catch (System.Exception ex)
            {
                _logger.LogError($"Error en el endpoint 'EditarTarea'. Detalles: {ex.ToString()}");
                return View("Error");
            }
        }


        [HttpPost]
        public IActionResult EditarTarea(ModificarTareaViewModel vm)
        {
            try
            {
                if (!Logueado())
                {
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
                if (!esAdmin())
                {
                    TempData["ErrorMessage"] = "No tienes permisos para editar un usuario";
                    return RedirectToAction("Index");
                }
                if (!ModelState.IsValid) return RedirectToAction("EditarTarea");

                var tarea2 = new Tarea(vm);

                repository.Update(tarea2.Id, tarea2);

                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                _logger.LogError($"Error en el endpoint 'EditarTarea'. Detalles: {ex.ToString()}");
                return View("Error");
            }
        }


        public IActionResult EliminarTarea(int Id)
        {
            try
            {
                if (!Logueado())
                {
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
                if (!ModelState.IsValid) return RedirectToAction("EditarTarea");

                repository.Remove(Id);

                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                _logger.LogError($"Error en el endpoint 'CrearTarea'. Detalles: {ex.ToString()}");
                return View("Error");
            }
        }

        public bool Logueado()
        {
            return HttpContext.Session.Keys.Any();
        }

        private bool esAdmin()
        {
            return HttpContext.Session.Keys.Any() && ((int)HttpContext.Session.GetInt32("rol") == 0);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Tarea/CrearTarea.cshtml
@model tl2_tp10_2023_NicoMagro.ViewModels.Tareas.CrearTareaViewModel

<form asp-controller="Tarea" asp-action="CrearTarea">

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Nombre" class="form-label"></label>
        <input asp-for="@Model.Nombre" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Estado" class="form-label"></label>
        <select asp-for="@Model.Estado" class="form-select" aria-label="Default select example">
            <option value="Ideas" selected>Ideas</option>
            <option value="ToDo">ToDo</option>
            <option value="Doing">Doing</option>
            <option value="Review">Review</option>
            <option value="Done">Done</option>
        </select>
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Descripcion" class="form-label"></label>
        <input asp-for="@Model.Descripcion" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Color" class="form-label"></label>
        <input asp-for="@Model.Color" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.IdUsuarioAsignado" class="form-label"></label>
        <input asp-for="@Model.IdUsuarioAsignado" class="form-control" />
    </div>

    <button type="submit" class="btn btn-info">Crear</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Tarea/EditarTarea.cshtml
@model tl2_tp10_2023_NicoMagro.ViewModels.Tareas.ModificarTareaViewModel

<form asp-controller="Tarea" asp-action="EditarTarea">
    <input hidden asp-for="@Model.Id">
    <div class="mb-3" class="form-group">
        <label asp-for="@Model.IdTablero" class="form-label"></label>
        <input asp-for="@Model.IdTablero" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Nombre" class="form-label"></label>
        <input asp-for="@Model.Nombre" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Estado" class="form-label"></label>
        <select asp-for="@Model.Estado" class="form-select" aria-label="Default select example">
            <option value="Ideas" selected>Ideas</option>
            <option value="ToDo">ToDo</option>
            <option value="Doing">Doing</option>
            <option value="Review">Review</option>
            <option value="Done">Done</option>
        </select>
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Descripcion" class="form-label"></label>
        <input asp-for="@Model.Descripcion" class="form-control" />
    </div>

    <div class="mb-3" class="form-group">
        <label asp-for="@Model.Color" class="form-label"></label>
        <input asp-for="@Model.Color" class="form-control" />
    </div>

    <button type="submit" class="btn btn-info">Editar</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Tarea/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model tl2_tp10_2023_NicoMagro.ViewModels.Tareas.ListarTareasViewModel

<h2>Listado de Tareas</h2>

<table class="table table-success table-striped">
    <thead>
        <tr>
            <th hidden>ID</th>
            <th>Id tablero</th>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Color</th>
            <th>Estado</th>
            <th>Id usuario asignado</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tarea in Model.ListadoTareas)
        {
            <tr>
                <td hidden>@tarea.Id</td>
                <td>@tarea.Id_tablero</td>
                <td>@tarea.Nombre</td>
                <td>@tarea.Descripcion</td>
                <td>@tarea.Color</td>
                <td>@tarea.Estado</td>
                <td>@tarea.IdUsuarioAsignado</td>
                <td>
                    <a asp-controller="Tarea" asp-action="EditarTarea" asp-route-Id="@tarea.Id"
                        class="btn btn-info">Editar</a>
                    <a asp-controller="Tarea" asp-action="EliminarTarea" asp-route-Id="@tarea.Id"
                        onclick="return confirm('¿Estás seguro que quieres eliminar la tarea?')"
                        class="btn btn-outline-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}